name: Check Baseball Ground Availability

on:
  schedule:
    # 毎日午前9時に実行
    - cron: '0 0 * * *'
  workflow_dispatch:  # 手動実行も可能に

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2.0.1
    
    - name: Start ChromeDriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 requests python-dotenv
    
    - name: Create .env file
      run: |
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
        echo "LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" >> .env
        echo "LINE_GROUP_ID=${{ secrets.LINE_GROUP_ID }}" >> .env
    
    - name: Run script
      run: python check_baseball_ground.py 