name: Check Baseball Ground Availability

on:
  schedule:
    # 毎日午前9時に実行
    - cron: '0 0 * * *'
  workflow_dispatch:  # 手動実行も可能に

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
  LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 requests python-dotenv
    
    - name: Install Chrome and ChromeDriver
      run: |
        # Chromeのインストール
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # ChromeDriverのインストール
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
        wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION.0.0/linux64/chromedriver-linux64.zip"
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    
    - name: Start ChromeDriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    
    - name: Run script
      run: |
        python check_baseball_ground.py
        if [ $? -ne 0 ]; then
          echo "Python script failed. Outputting error log:"
          cat error.log || echo "No error log found"
          exit 1
        fi

    - name: Output error log if failed
      if: failure()
      run: |
        echo "Workflow failed. Outputting error log:"
        cat error.log || echo "No error log found"
      continue-on-error: true 